import hfut

a = hfut.Webvpn()
a.get_portals()
print(a.portals)
b = hfut.JxglWebvpn(a)
b.login()
print('====================================== semester list ======================================')
print(b.get_semester_list())
print('====================================== course data ======================================')
print(b.get_course_data())
print('====================================== schedule data ======================================')
print(b.get_schedule_data())
print('====================================== exam arrange ======================================')
print(b.get_exam_arrange())
print('====================================== score data ======================================')
print(b.get_score_data())
print('====================================== lesson survy ======================================')
print(b.get_lesson_survy_data())
print('====================================== search lesson ======================================')
print(b.search_lesson())