import hfut
from hfut.tools import rand_sleep

webvpn = hfut.Webvpn()
webvpn.login()
rand_sleep(2, 5)
print(webvpn.get_portals())
print('==================== webvpn portals ====================')
rand_sleep(2, 5)

jxgl_webvpn = webvpn.get_jxgl_webvpn()
jxgl_webvpn.login()
rand_sleep(2, 5)
print(jxgl_webvpn.get_semester_list())
print('==================== jxgl webvpn semester list ====================')
rand_sleep(2, 5)
print(jxgl_webvpn.get_course_data())
print('==================== jxgl webvpn course data ====================')
rand_sleep(2, 5)
print(jxgl_webvpn.get_schedule_data())
print('==================== jxgl webvpn schedule data ====================')
rand_sleep(2, 5)
print(jxgl_webvpn.get_exam_arrange())
print('==================== jxgl webvpn exam arrange ====================')
rand_sleep(2, 5)
print(jxgl_webvpn.get_score_data())
print('==================== jxgl webvpn score data ====================')
rand_sleep(2, 5)
print(jxgl_webvpn.get_lesson_survy_data())
print('==================== jxgl webvpn lesson survy ====================')
rand_sleep(2, 5)
print(jxgl_webvpn.search_lesson(custom_params={'courseNameZhLike': '数学'}))
print('==================== jxgl webvpn search lession 数学 ====================')
rand_sleep(2, 5)

jxgl_mobile = hfut.JxglMobile()
jxgl_mobile.login()
rand_sleep(2, 5)
print(jxgl_mobile.get_user_info())
print('==================== jxgl mobile user info ====================')
rand_sleep(2, 5)
print(jxgl_mobile.get_semester_list())
print('==================== jxgl mobile semester list ====================')
rand_sleep(2, 5)
print(jxgl_mobile.get_week_schedule())
print('==================== jxgl mobile week schedule ====================')
rand_sleep(2, 5)
print(jxgl_mobile.get_classmates('0100005X--001'))
print('==================== jxgl mobile classmate 0100005X--001 ====================')